name = "Carpet"
filename = "fabric-carpet-1.17.1-1.4.56+v211130.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/17/fabric-carpet-1.17.1-1.4.56+v211130.jar"
hash-format = "murmur2"
hash = "1579331879"

[update]
[update.curseforge]
file-id = 3542017
project-id = 349239
release-channel = "beta"
