name = "VoxelMap"
filename = "fabricmod_VoxelMap-1.10.15_for_1.17.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3345/206/fabricmod_VoxelMap-1.10.15_for_1.17.0.jar"
hash-format = "murmur2"
hash = "663028775"

[update]
[update.curseforge]
file-id = 3345206
project-id = 225179
release-channel = "beta"
